# Moshikur IGCSE CS sub-topic URLs
# Fill in the URL for each sub-topic you want to scrape.
# Leave out (or comment out) any sub-topics not covered by the site.

URLS = {

    "CH 01 Data Representation": "https://moshikur.com/igcse-o-level-cs/ch-01-data-representation/",
    "1.1 Number System": "https://moshikur.com/igcse-o-level-cs/ch-01-data-representation/1-1-data-representation/",
    "1.2 Text, Sound, and Images": "https://moshikur.com/igcse-o-level-cs/ch-01-data-representation/1-2-text-sound-and-images/",
    "1.3 Compression": "https://moshikur.com/igcse-o-level-cs/ch-01-data-representation/1-3-data-storage-and-compression/",
    "CH 02 Data Transmission": "https://moshikur.com/igcse-o-level-cs/ch-02-data-transmission/",
    "2.1 Types and Methods of Data Transmission": "https://moshikur.com/igcse-o-level-cs/ch-02-data-transmission/2-1-types-and-methods-of-data-transmission/",
    "2.2 Methods of Error Detection": "https://moshikur.com/igcse-o-level-cs/ch-02-data-transmission/2-2-methods-of-error-detection/",
    "2.3 Encryption": "https://moshikur.com/igcse-o-level-cs/ch-02-data-transmission/2-3-encryption/",
    "CH 03 Hardware": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/",
    "3.1 Computer Architecture": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/3-1-computer-architecture/",
    "3.2 Input/Output Devices": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/3-2-input-output-devices/",
    "3.2.1 INPUT Devices": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/3-2-input-output-devices/3-2-1-input-devices/",
    "3.2.2 Output Devices": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/3-2-input-output-devices/3-2-2-output-devices/",
    "3.2.3 Sensors": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/3-2-input-output-devices/3-2-3-sensors/",
    "3.3 Storage Devices and Media": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/3-3-storage-devices-and-media/",
    "3.4 Network Concepts": "https://moshikur.com/igcse-o-level-cs/chapter-3-hardware/3-4-network-concepts/",
    "CH 04 Software": "https://moshikur.com/igcse-o-level-cs/ch-04-software/",
    "4.1 Types of software and interrupts": "https://moshikur.com/igcse-o-level-cs/ch-04-software/4-1-types-of-software-and-interrupts/",
    "4.2 Types of programming language, translators and integrated development environments (IDEs)": "https://moshikur.com/igcse-o-level-cs/ch-04-software/4-2-types-of-programming-language-translators-and-integrated-development-environments-ides/",
    "CH 05 The Internet and Its Uses": "https://moshikur.com/igcse-o-level-cs/ch-05-the-internet-and-its-uses/",
    "5.1 The internet and the world wide web": "https://moshikur.com/igcse-o-level-cs/ch-05-the-internet-and-its-uses/5-1-the-internet-and-the-world-wide-web/",
    "5.2 Digital Currency": "https://moshikur.com/igcse-o-level-cs/ch-05-the-internet-and-its-uses/5-2-digital-currency/",
    "5.3 Cyber Security": "https://moshikur.com/igcse-o-level-cs/ch-05-the-internet-and-its-uses/5-3-cyber-security/",
    "CH 06 Automated and Emerging Technologies": "https://moshikur.com/igcse-o-level-cs/ch-06-automated-and-emerging-technologies/",
    "6.1 Automated Systems": "https://moshikur.com/igcse-o-level-cs/ch-06-automated-and-emerging-technologies/6-1-automated-systems/",
    "6.2 Robotics": "https://moshikur.com/igcse-o-level-cs/ch-06-automated-and-emerging-technologies/6-2-robotics/",
    "6.3 Artificial Intelligence": "https://moshikur.com/igcse-o-level-cs/ch-06-automated-and-emerging-technologies/6-3-artificial-intelligence/",
    "CH 07 Algorithm Design & Problem Solving": "https://moshikur.com/igcse-o-level-cs/ch-07-algorithm-design-and-problem-solving/",
    "CH 08 Programming": "https://moshikur.com/igcse-o-level-cs/ch-08-programming/",
    "CH 09 Databases": "https://moshikur.com/igcse-o-level-cs/ch-09-databases/",
    "CH 10 Boolean Logic": "https://moshikur.com/igcse-o-level-cs/ch-10-boolean-logic/",

    "PSEUDOCODE": "https://moshikur.com/pseudocode/",
    "Introduction": "https://moshikur.com/pseudocode/introduction-to-pseudocode/",
    "FlowchartS": "https://moshikur.com/igcse-o-level-cs/ch-07-algorithm-design-and-problem-solving/5-2-algorith-flowchart/",
    "1 PSEUDOCODE Variables and Data Types": "https://moshikur.com/pseudocode/1-pseudocode-variables-and-data-types/",
    "2 PSEUDOCODE Assignment, Input & Output": "https://moshikur.com/pseudocode/pseudocode-assignment-input-output/",
    "3 CONDITIONAL STATEMENTS": "https://moshikur.com/pseudocode/3-conditional-statements/",
    "3.1 Pseudocode If Then Else": "https://moshikur.com/pseudocode/3-conditional-statements/pseudocode-if-then-else/",
    "3.2 CASE OF STATEMENTS": "https://moshikur.com/pseudocode/3-conditional-statements/3-2-case-of-statements/",
    "3.3 Nested IF Statements": "https://moshikur.com/pseudocode/3-conditional-statements/4-3-nested-if-statements/",
    "4 Pseudocode Operators": "https://moshikur.com/pseudocode/3-pseudocode-operators/",
    "5 PSEUDOCODE LOOPS": "https://moshikur.com/pseudocode/pseudocode-loops/",
    "5.1 For Loop": "https://moshikur.com/pseudocode/pseudocode-loops/4-1-for-loop/",
    "5.2 Pseudocode Repeat Until Loop": "https://moshikur.com/pseudocode/pseudocode-loops/pseudocode-repeat-until-loop/",
    "5.3 Pseudocode While Loop": "https://moshikur.com/pseudocode/pseudocode-loops/pseudocode-while-loop/",
    "5.4 Loops with Boolean Flags": "https://moshikur.com/pseudocode/pseudocode-loops/4-4-loops-with-boolean-flags/",
    "5.5 Pseudocode Nested Loop": "https://moshikur.com/pseudocode/pseudocode-loops/4-4-pseudocode-nested-loop/",
    "6 PSEUDOCODE Common Operations": "https://moshikur.com/pseudocode/6-pseudocode-basic-operations/",
    "6.1 Pseudocode Counting": "https://moshikur.com/pseudocode/6-pseudocode-basic-operations/5-1-pseudocode-counting/",
    "6.2 Pseudocode Totaling": "https://moshikur.com/pseudocode/6-pseudocode-basic-operations/6-2-pseudocode-totaling/",
    "6.3 Pseudocode Finding Highest/Lowest Value": "https://moshikur.com/pseudocode/6-pseudocode-basic-operations/5-3-pseudocode-finding-highest-lowest-value/",
    "6.4 Validation & Verification": "https://moshikur.com/pseudocode/6-pseudocode-basic-operations/5-4-validation-verification/",
    "6.5 Using Trace Tables": "https://moshikur.com/pseudocode/6-pseudocode-basic-operations/5-6-using-trace-tables/",
    "Practice Tasks": "https://moshikur.com/pseudocode/6-pseudocode-basic-operations/practice-tasks/",
    "7 PSEUDOCODE ARRAY": "https://moshikur.com/pseudocode/6-pseudocode-array/",
    "7.1 ARRAY TASKS": "https://moshikur.com/pseudocode/6-pseudocode-array/6-1-pseudocode-tasks/",
    "7.2 Array Tasks": "https://moshikur.com/pseudocode/6-pseudocode-array/6-1-2-array-tasks-1-2/",
    "7.3 ARRAY TASKS": "https://moshikur.com/pseudocode/6-pseudocode-array/6-1-pseudocode-array-tasks-2/",
    "7.4 LINEAR SEARCH": "https://moshikur.com/pseudocode/6-pseudocode-array/6-2-pseudocode-linear-search/",
    "7.5 PSEUDOCODE Bubble Sort": "https://moshikur.com/pseudocode/6-pseudocode-array/7-pseudocode-bubble-sort/",
    "8 PSEUDOCODE STRING MANIPULATION": "https://moshikur.com/pseudocode/7-pseudocode-string-manipulation/",
    "IGCSE/O Level String Manipulation": "https://moshikur.com/pseudocode/7-pseudocode-string-manipulation/7-1-igcse-o-level-string-manipulation/",
    "9 PSEUDOCODE Text File Handling": "https://moshikur.com/pseudocode/8-pseudocode-text-file-handling/",
    "IGCSE/O Level Text File Handling": "https://moshikur.com/pseudocode/8-pseudocode-text-file-handling/igcse-o-level-text-file-handling/",
    "10 Pseudocode Library Routines": "https://moshikur.com/pseudocode/10-pseudocode-library-routines/",
    "Random Number Generation": "https://moshikur.com/pseudocode/random-number-generation/",
    "Round & Random for Igcse": "https://moshikur.com/pseudocode/random-number-generation/understanding-random-and-round-in-igcse/",
    "11 Pseudocode Functions & Procedures": "https://moshikur.com/pseudocode/11-pseudocode-functions-procedures/",
    "12 PSEUDOCODE 2D Array": "https://moshikur.com/pseudocode/9-pseudocode-2d-array/",
}

# Full 0478 syllabus — used by the scraper to generate the audit report
SYLLABUS = {
    "1.1": "Number Systems",
    "1.2": "Text, Sound and Images",
    "1.3": "Data Storage and Compression",
    "2.1": "Types and Methods of Data Transmission",
    "2.2": "Methods of Error Detection",
    "2.3": "Encryption",
    "3.1": "Computer Architecture",
    "3.2": "Input and Output Devices",
    "3.3": "Data Storage",
    "3.4": "Network Hardware",
    "4.1": "Types of Software and Interrupts",
    "4.2": "Types of Programming Language, Translators and IDEs",
    "5.1": "The Internet and the World Wide Web",
    "5.2": "Digital Currency",
    "5.3": "Cyber Security",
    "6.1": "Automated Systems",
    "6.2": "Robotics",
    "6.3": "Artificial Intelligence",
    "7.1": "Program Development Life Cycle",
    "7.2": "Problem Decomposition",
    "7.3": "Algorithm Design Methods",
    "7.4": "Standard Methods of Solution",
    "7.5": "Validation and Verification",
    "7.6": "Testing",
    "7.7": "Trace Tables",
    "7.8": "Error Identification",
    "8.1": "Programming Concepts",
    "8.2": "Arrays",
    "8.3": "File Handling",
    "9.1": "Database Design",
    "9.2": "SQL Queries",
    "10.1": "Logic Gates",
    "10.2": "Logic Circuits",
    "11.1": "Writing Pseudocode for Context Scenario",
}

# Explicit mapping: chapter-level page keys → 0478 sub-topic codes they cover
# Used by the audit when a single page covers an entire topic.
CHAPTER_SYLLABUS_MAP = {
    "CH 07 Algorithm Design & Problem Solving": ["7.1", "7.2", "7.3", "7.4", "7.5", "7.6", "7.7", "7.8"],
    "CH 08 Programming": ["8.1", "8.2", "8.3"],
    "CH 09 Databases": ["9.1", "9.2"],
    "CH 10 Boolean Logic": ["10.1", "10.2"],
}

# Maps topic number prefix to output folder name
TOPIC_DIRS = {
    "1": "topic1_data_representation",
    "2": "topic2_data_transmission",
    "3": "topic3_hardware",
    "4": "topic4_software",
    "5": "topic5_internet_and_uses",
    "6": "topic6_automated_emerging",
    "7": "topic7_algorithm_design",
    "8": "topic8_programming",
    "9": "topic9_databases",
    "10": "topic10_boolean_logic",
    "11": "topic11_scenario_algorithm",
}
